

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096" # HTTP (puerto por defecto de Jellyfin)
    volumes:
      - ./config:/config
      - ./media:/media
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
