services:
  ejabberd:
    image: ghcr.io/processone/ejabberd:latest
    container_name: ejabberd
    restart: unless-stopped
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
    volumes:
      - ./ejabberd-data/conf/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
      # - ./ejabberd-data/database:/opt/ejabberd/database
